// Generated by CoffeeScript 1.6.2
(function() {
  var initApp;

  initApp = function() {
    var el, objData, objDataLines;
    console.log("Running Three Hub");
    objDataLines = $(".blob-line-code pre .line").map(function() {
      return $(this).text();
    });
    objData = objDataLines.toArray().join("\n");
    el = $(".blob-wrapper.js-blob-data");
    el.html("");
    objScene.drawObj(objData, el.get(0), 912, 465);
    el.append(uicontrols.template);
    return uicontrols.bindEvents();
  };

  $(initApp);

  console.log("Three Hub (https://github.com/danielribeiro/three-hub) loaded");

}).call(this);
